
[build]
  base    = "landing"
  publish = "landing/build"
  command = "yarn build --type=UMD_DEV && cd landing && yarn && yarn prestart && yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200