export const tempstate = {
	devProjectList: [
		{
			"ownerProfilePicture": "https://thispersondoesnotexist.com/image",
			"ownerName": "Alfonso Garcia",
			"owner": "5d5dd28cf58b080017a4db57",
			"name": "Not DevFindr v2",
			"price": 50000,
			"status": "progress",
		},
		{
			"ownerProfilePicture": "https://thispersondoesnotexist.com/image",
			"ownerName": "Joseph Jalapeno",
			"owner": "5d5dd28cf58b080017a4db57",
			"name": "Social Manager for Influencers",
			"price": 3000,
			"status": "completed",
		},
		{
			"ownerProfilePicture": "https://thispersondoesnotexist.com/image",
			"ownerName": "Chris Doe",
			"owner": "5d5dd28cf58b080017a4db57",
			"name": "Client Manager",
			"price": 308442,
			"status": "cancelled",
		},
		{
			"ownerProfilePicture": "https://thispersondoesnotexist.com/image",
			"ownerName": "Alexis Garcia",
			"owner": "5d5dd28cf58b080017a4db57",
			"name": "LambdaSchool Student Management",
			"price": 53423156,
			"status": "cancelled",
		},
		{
			"ownerProfilePicture": "https://thispersondoesnotexist.com/image",
			"ownerName": "Lilliana Splenduval",
			"owner": "5d5dd28cf58b080017a4db57",
			"name": "Big Picture student manager",
			"price": 352235,
			"status": "cancelled",
		},
		{
			"ownerProfilePicture": "https://thispersondoesnotexist.com/image",
			"ownerName": "Junior Buttsnack",
			"owner": "5d5dd28cf58b080017a4db57",
			"name": "The Snack That Smiles Back",
			"price": 53156,
			"status": "completed",
		},
		{
			"ownerProfilePicture": "https://thispersondoesnotexist.com/image",
			"ownerName": "Mikey Fretos",
			"owner": "5d5dd28cf58b080017a4db57",
			"name": "Fretos Invitory Management",
			"price": 21,
			"status": "review",
		},
		{
			"ownerProfilePicture": "https://thispersondoesnotexist.com/image",
			"ownerName": "Steve Jubil",
			"owner": "5d5dd28cf58b080017a4db57",
			"name": "Freelancing Network",
			"price": 6358413,
			"status": "completed",
		},
		{
			"ownerProfilePicture": "https://thispersondoesnotexist.com/image",
			"ownerName": "Jason Bar",
			"owner": "5d5dd28cf58b080017a4db57",
			"name": "Barful Tracking",
			"price": 94935,
			"status": "completed",
		},
	]
}
